version: '3.8'

services:
  app:
    container_name: mockup-api-doctor-ease
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6301:6301"
    environment:
      - NODE_ENV=production